// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs4Mr0X2zhGvoLjNOtjpvp2MUV4ZpAspg',
    appId: '1:565657632479:web:099ad1a65b12a0d13e336a',
    messagingSenderId: '565657632479',
    projectId: 'chatthub-5d707',
    authDomain: 'chatthub-5d707.firebaseapp.com',
    storageBucket: 'chatthub-5d707.firebasestorage.app',
    measurementId: 'G-5RQVZ57N4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbSRh6_zFAQT999i_FY8dnQOXuizp3OMI',
    appId: '1:565657632479:android:29dd5df192f4dd043e336a',
    messagingSenderId: '565657632479',
    projectId: 'chatthub-5d707',
    storageBucket: 'chatthub-5d707.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKf5C_HYc1ioWJZqWEFFL6CefiNHa3lV4',
    appId: '1:565657632479:ios:658fd4faa6868a4b3e336a',
    messagingSenderId: '565657632479',
    projectId: 'chatthub-5d707',
    storageBucket: 'chatthub-5d707.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKf5C_HYc1ioWJZqWEFFL6CefiNHa3lV4',
    appId: '1:565657632479:ios:658fd4faa6868a4b3e336a',
    messagingSenderId: '565657632479',
    projectId: 'chatthub-5d707',
    storageBucket: 'chatthub-5d707.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs4Mr0X2zhGvoLjNOtjpvp2MUV4ZpAspg',
    appId: '1:565657632479:web:06b92e76ed14682a3e336a',
    messagingSenderId: '565657632479',
    projectId: 'chatthub-5d707',
    authDomain: 'chatthub-5d707.firebaseapp.com',
    storageBucket: 'chatthub-5d707.firebasestorage.app',
    measurementId: 'G-XWMGERDB0K',
  );
}
